version: 0.0
os: linux
files:
  - source: ./codebuildtestlisy/MyPath/WeGetDemo/*
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/before_install
      timeout: 300
      runas: root
  AfterInstall:
    - location: after_server
      timeout: 300
      runas: root
  ApplicationStart:
    - location: start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: stop_server
      timeout: 300
      runas: root
