version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  Before Install:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root
  After Install:
    - location: scripts/after_install.sh
      timeout: 300
      runas: root
  Application Start:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  Application Stop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
