version: 0.0
os: linux
files:
  - source:  https://codebuildtestlisy.s3-ap-northeast-1.amazonaws.com/MyPath/WeGetdemo.war
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/before_install
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/after_install
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
