version: 0.0
os: linux
files:
  - source: s3://codebuildtestlisy/MyPath/WeGetDemo/*
    destination: /var/www/html
hooks:
  BeforeInstall:
    - location: scripts/before_install
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/after_server
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
  #ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
