version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10  
  pre_build:
    commands:
    - echo Installing all the dependencies
    - yum install zip -y
    - npm install --global --production windows-build-tools
    - npm install node-sass
    - npm install
    - npm run dev
  
  
