version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10  
  pre_build:
    commands:
    - echo Installing all the dependencies
    - yum install zip -y
    - npm --prefix server/ install 
  
  
