version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo Install node_modules
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build

artifacts:
  files:
    - 'dist/**/*'
  name: dist-$(date +%Y-%m-%d)
    - "aws s3 cp --recursive s3://<toaindcodebuild-output>/ ."

cache:
  paths:
    - 'node_modules/**/*'
    - "aws s3 cp --recursive s3://<toaindcodebuild-output>/ ."
    
    
  
  
