version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo Install node_modules
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build: 
      commands:
      - echo Build started on `date`   
artifacts:
      files:
        - './dist/**/*'
        # - './.github/dev/appspec.yml'
        # - './.github/dev/scripts/*'
      discard-paths:  yes
      secondary-artifacts:
        artifact1:
          files:
            - './.github/dev/appspec.yml'
          discard-paths:  yes
        artifact2:
          files:
            - './.github/dev/**'
          discard-paths:  yes

         
   
  
      
      
     
 
