version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo Install node_modules
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build

  post_build: 
      commands:
      - echo Build started on `date`
artifacts:
   run: |
      aws s3 sync ./ s3://${{ secrets.AWS_S3_BUCKET }}/codebuild/
        
    
    
  
  
