# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# This workflow contains a single job called "build"
jobs:
 deploy:
    name: Build And Upload to S3
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Build
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: yarn
    - run: yarn build
    
    - name: Configure AWS credentials from account
      uses: aws-actions/configure-aws-credentials@v1
      
    
    - name: Copy Files to s3
      run: |
        aws s3 sync ./public s3://bucketfromgit
